# Use official Node image
FROM node:20

# Set working directory inside container
WORKDIR /var/www

# Copy only dependency files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project
COPY . .

