FROM php:8.3-fpm

# 2. Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    curl \
    && docker-php-ext-install pdo_mysql zip

# 3. Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# 4. Set working directory
WORKDIR /var/www

# 5. Copy full project first (needed for artisan scripts)
COPY . .

# 6. Install PHP dependencies
RUN composer install --no-interaction --prefer-dist

